
require_relative 'test_center_utils'

# Retrieves the example code from each action and runs it to ensure that everything
# is working as intended.
lane :run_examples do
  action_examples.values.flatten.each do |example_code_snippet|
    # rubocop:disable Security/Eval
    eval(example_code_snippet)
    # rubocop:enable Security/Eval
  end
end

lane :json do
  UI.important(
    'example: ' \
    'multi_scan also works with xcpretty-json-formatter.'
  )
  ENV['XCPRETTY_JSON_FILE_OUTPUT'] = File.absolute_path('./test_output/report.json')
  multi_scan(
    workspace: File.absolute_path('../AtomicBoy/AtomicBoy.xcworkspace'),
    scheme: 'AtomicBoy',
    try_count: 3,
    output_types: 'json'
  )
end
